// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumView = { id: number, name: string, kind: string, member_count: number, has_password: boolean, unlocked: boolean, hidden: boolean, };
