// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One detected face within a single asset, for the viewer face overlay.
 *
 * `bbox` is xywh in thumb1024 pixel space (same coord space the viewer
 * renders from), so the client scales to % for CSS positioning.
 */
export type AssetFaceView = { face_id: number, person_id: number | null, person_name: string | null, bbox: [number, number, number, number], quality: number, };
