// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpsView } from "./GpsView";

export type AssetDetailView = { id: number, mime: string, bytes: number, width: number | null, height: number | null, duration_ms: number | null, taken_at_utc_day: number | null, is_video: boolean, is_live: boolean, is_motion: boolean, is_raw: boolean, is_screenshot: boolean, filename: string, taken_at_utc: string | null, gps: GpsView | null, device: string | null, lens: string | null, exif_json: string | null, };
