// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a bundle. Persisted to `<vault>/models/bundle.json`
 * so the loader knows which SHA-256 pins to verify against on startup.
 */
export type BundleId = "full" | "lite";
