// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress events the downloader streams back to the UI. The Tauri command
 * layer serialises these onto the `ml-download-event` channel.
 */
export type DownloadEvent = { "kind": "start", name: string, bytes_total: number, } | { "kind": "progress", name: string, bytes_downloaded: number, bytes_total: number, } | { "kind": "verified", name: string, } | { "kind": "file_failed", name: string, reason: string, } | { "kind": "all_done", ok: boolean, failed: Array<string>, };
