// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportReport = { files_written: number, bytes_written: number, xmp_written: number, skipped: number, };
