// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncomingShareView = { collection_id: number, namespace_id_hex: string, sender_identity_pub_hex: string, 
/**
 * `"pending"` = namespace joined, no collection key yet.
 * `"accepted"` = key unwrapped + album rendered.
 * `"revoked"` = tombstone received.
 */
state: string, 
/**
 * Populated once the first `c/meta/` event decrypts. Until then
 * the UI shows "(incoming share)".
 */
album_name: string | null, };
