// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IngestState = { "state": "idle" } | { "state": "running", files_processed: number, files_total: number, current: string | null, } | { "state": "done", inserted: number, deduped: number, skipped: number, errors: number, } | { "state": "failed", message: string, };
