// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngestState } from "./IngestState";

export type IngestStatus = { source_id: number, state: IngestState, };
