// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapPoint = { asset_id: number, lat: number, lon: number, taken_at_utc_day: number | null, };
