// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryGroupView = { 
/**
 * Year the photos were taken in.
 */
year: number, 
/**
 * Years ago relative to today ("1 year ago", "5 years ago").
 */
years_ago: number, 
/**
 * Asset ids ordered; the UI pages/thumbnails from these.
 */
asset_ids: Array<number>, };
