// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlReindexReport = { 
/**
 * Jobs newly inserted for CLIP embedding. Dedupes are excluded.
 */
embed_queued: number, 
/**
 * Jobs newly inserted for face detection + embedding.
 */
detect_queued: number, 
/**
 * Distinct assets that at least one sweep hit — useful for showing a
 * single "N assets reindexed" number.
 */
assets_touched: number, };
