// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlStatus = { models_available: boolean, pending: number, running: number, done: number, failed: number, };
