// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlStatus = { 
/**
 * `true` when the app was built with `--features ml-models`. Says nothing
 * about whether weights are actually loaded — see `runtime_loaded`.
 */
models_available: boolean, 
/**
 * `true` when the on-device ML runtime has loaded (weights + tokenizer
 * live in memory, ort sessions ready). Implies `models_available`.
 */
runtime_loaded: boolean, 
/**
 * Human-readable execution provider the runtime picked ("Cpu", "Cuda",
 * "CoreMl", or "disabled" when `runtime_loaded=false`). Shown in the
 * banner so users can verify where inference is actually running.
 */
execution_provider: string, pending: number, running: number, done: number, failed: number, };
