// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Survey result for one manifest entry.
 */
export type ModelFileStatus = { name: string, 
/**
 * File exists on disk (regardless of integrity).
 */
present: boolean, 
/**
 * File matches the pinned SHA-256. Always false when `present` is false.
 */
valid: boolean, 
/**
 * Bytes on disk. Zero when the file is missing.
 */
size_bytes: number, 
/**
 * Pinned hex SHA-256, for UI display / support-bundle purposes.
 */
sha256_expected: string, };
