// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelFileStatus } from "./ModelFileStatus";

/**
 * Snapshot of every manifest entry's presence + integrity.
 */
export type ModelsStatus = { files: Array<ModelFileStatus>, 
/**
 * True only when every file is present AND its checksum matches. The UI
 * uses this for the "skip download" vs "start download" decision.
 */
all_present_valid: boolean, };
