// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NearDupMember } from "./NearDupMember";

export type NearDupCluster = { cluster_id: number, members: Array<NearDupMember>, };
