// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairingTicketView = { 
/**
 * Base32-encoded ticket to copy/paste or render as a QR. Always
 * lowercase RFC4648 without padding.
 */
base32: string, 
/**
 * Hex of the signer's 32-byte Ed25519 node id. Useful for the UI to
 * show "my node: abc12345…" next to the ticket.
 */
my_node_id_hex: string, 
/**
 * UNIX seconds the ticket was signed at.
 */
created_at: number, };
