// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerAcceptedView = { 
/**
 * Hex of the remote node id. UI truncates for display.
 */
node_id_hex: string, 
/**
 * Hex of the remote X25519 identity public key. Phase 3.2 consumers use
 * this to seal collection keys back.
 */
identity_pub_hex: string, 
/**
 * `None` = LAN-only; `Some` = relay the remote published.
 */
relay_url: string | null, added_at: number, };
