// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D3-follow-up §8b "Person X in Year Y" card.
 */
export type PersonYearMemoryView = { person_id: number, year: number, asset_ids: Array<number>, };
