// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonView = { id: number, name: string | null, hidden: boolean, face_count: number, cover_asset_id: number | null, };
