// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D9 pet asset row. `species` is decrypted from `pet_species_ct`
 * server-side; `None` means flagged-as-pet without a species label.
 */
export type PetAssetView = { id: number, taken_at_utc_day: number | null, species: string | null, };
