// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 4 D2 follow-up: a place where the library has photos,
 * produced by reverse-geocoding every GPS-tagged asset and grouping
 * by `{country, city}`. Powers the new "Places" surfaces (For-You
 * carousel, Albums sub-section, EntityChip drill-in, universal search).
 */
export type PlaceView = { 
/**
 * Stable id `"{country}:{city}"` — used as the routing key for
 * the Place screen. Identical to `format!("{}:{}", country, city)`
 * so callers can reconstruct it without round-tripping the API.
 */
place_id: string, city: string, region: string, country: string, 
/**
 * Total photos at this place across the user's library.
 */
asset_count: number, 
/**
 * Up to 6 asset ids to populate hero strips and place cards. Drawn
 * across the time range so the cover doesn't degenerate to one day.
 */
sample_asset_ids: Array<number>, 
/**
 * Centroid of the photos at this place — used to position map
 * markers and for distance-based filtering. Plain coords, not
 * encrypted, since the place itself is already plaintext.
 */
centroid_lat: number, centroid_lon: number, };
