// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D7 public share-link, as returned to the UI. `url_fragment` is only
 * populated on create — a subsequent `list_public_links` call can't
 * recover the viewer key, so re-sharing a lost link requires creating
 * a new one (and revoking the old).
 */
export type PublicLinkView = { id: number, collection_id: number, 
/**
 * Lowercase base32 of the 16-byte `pub_id`. Compose the URL as
 * `https://<host>/s/<pub_id_b32>[#<url_fragment>]`.
 */
pub_id_b32: string, 
/**
 * Hex-free base32 fragment. Present on create for no-password
 * links; empty string when password-gated or when the link was
 * returned by a list command (the key isn't recoverable then).
 */
url_fragment: string, has_password: boolean, expires_at: number | null, created_at: number, };
