// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D7a bundle-export result. `file_path` is an absolute filesystem
 * path to the HTML written on disk. `url_fragment` is populated for
 * no-password links so the sender can append `#<fragment>` when
 * hosting the HTML over HTTP; password-gated bundles leave it empty.
 */
export type PublicLinkBundleReport = { pub_id_b32: string, url_fragment: string, has_password: boolean, asset_count: number, file_path: string, expires_at: number | null, };
