// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchRequest = { text: string | null, person_ids: Array<bigint>, after_day: number | null, before_day: number | null, source_id: number | null, has_faces: boolean | null, is_video: boolean | null, is_raw: boolean | null, is_screenshot: boolean | null, is_live: boolean | null, camera_make: string | null, lens: string | null, limit: number, };
