// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionHandle = { user_id: number, username: string, default_collection_id: number, hidden_unlocked: boolean, };
