// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareRecipientView = { 
/**
 * Peer node id (Ed25519) in hex — matches what peer_list returns.
 */
peer_node_id_hex: string, 
/**
 * Peer identity public key (X25519) in hex — the recipient's
 * seal/open handle.
 */
peer_identity_pub_hex: string, 
/**
 * Iroh relay URL the recipient published (None for LAN-only).
 */
relay_url: string | null, 
/**
 * UNIX seconds when the wrapping landed on the sender side. Not
 * when the recipient accepted it — the sender has no way to know
 * that without an explicit ack.
 */
shared_at: number, };
