// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareInviteView = { 
/**
 * Base32-encoded iroh-docs `DocTicket`. Paste into the recipient's
 * "Accept invite" textarea to subscribe to the namespace.
 */
namespace_ticket_base32: string, collection_id: number, asset_count: number, };
