// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartRuleView } from "./SmartRuleView";

export type SmartAlbumView = { id: number, 
/**
 * Decrypted display name.
 */
name: string, 
/**
 * Rule that produced this album's snapshot.
 */
rule: SmartRuleView, 
/**
 * Last materialised count. Stale until `refresh_smart_album` runs.
 */
member_count: number, 
/**
 * UNIX seconds of the last refresh. `None` when the album was
 * created but never materialised (shouldn't happen — create always
 * refreshes — but kept nullable for UI safety).
 */
snapshot_at: number | null, created_at: number, };
