// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D4 rule spec. Mirrors `mv_core::analytics::smart_albums::SmartRule`
 * 1:1 so the UI can author a rule without reaching into a separate
 * crate. Fields default to `null` (all) or `[]` (person ids) — the
 * `any` empty-rule check lives on the command side, not in types.
 */
export type SmartRuleView = { is_raw: boolean | null, is_video: boolean | null, is_screenshot: boolean | null, is_live: boolean | null, has_faces: boolean | null, camera_make: string | null, lens: string | null, source_id: number | null, person_ids: Array<number>, after_day: number | null, before_day: number | null, };
