// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceView = { id: number, name: string, root_path: string, adapter_kind: string, linked_only: boolean, bytes_total: number, file_count: number, imported_at: number, };
