// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineEntryView = { id: number, taken_at_utc_day: number | null, mime: string, is_video: boolean, is_live: boolean, is_raw: boolean, };
