// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineCursor } from "./TimelineCursor";
import type { TimelineEntryView } from "./TimelineEntryView";

export type TimelinePage = { entries: Array<TimelineEntryView>, next_cursor: TimelineCursor | null, };
