// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TripView = { id: number, 
/**
 * Decrypted trip name — e.g. "Trip · 12 photos · day 20050..20055".
 * D2 (reverse geocoding) will replace this with "Tokyo, 2024".
 */
name: string, member_count: number, created_at: number, };
