// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D6 multi-user summary. Surfaced pre-unlock on the login screen and
 * post-unlock in the same-device share picker. Username stays sealed
 * — callers can render "User #{user_id}" until the typed-in username
 * unlocks the row.
 */
export type UserSummaryView = { user_id: number, 
/**
 * X25519 public key in hex. Matches the bytes we hand remote peers
 * when sealing a collection key — the same ID space is reused for
 * same-device sharing.
 */
identity_pub_hex: string, created_at: number, };
