// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D3-follow-up §8b "year in photos" card.
 */
export type YearInPhotosView = { year: number, asset_count: number, 
/**
 * Up to 6 representative asset ids drawn across the year.
 */
highlights: Array<number>, };
