// Typed IPC wrappers. Generated DTOs live in `./bindings/` (regenerated by
// `pnpm --filter app tauri` tests, or via `scripts/codegen_ts.sh`).
import { invoke } from "@tauri-apps/api/core";

export type { AlbumView } from "./bindings/AlbumView";
export type { AssetDetailView } from "./bindings/AssetDetailView";
export type { AssetFaceView } from "./bindings/AssetFaceView";
export type { ExportOptions } from "./bindings/ExportOptions";
export type { ExportReport } from "./bindings/ExportReport";
export type { GpsView } from "./bindings/GpsView";
export type { IngestState } from "./bindings/IngestState";
export type { IngestStatus } from "./bindings/IngestStatus";
export type { MapPoint } from "./bindings/MapPoint";
export type { MlStatus } from "./bindings/MlStatus";
export type { MlReindexReport } from "./bindings/MlReindexReport";
export type { PairingTicketView } from "./bindings/PairingTicketView";
export type { PeerAcceptedView } from "./bindings/PeerAcceptedView";
export type { ShareInviteView } from "./bindings/ShareInviteView";
export type { ShareRecipientView } from "./bindings/ShareRecipientView";
export type { IncomingShareView } from "./bindings/IncomingShareView";
export type { TripView } from "./bindings/TripView";
export type { MemoryGroupView } from "./bindings/MemoryGroupView";
export type { SmartAlbumView } from "./bindings/SmartAlbumView";
export type { SmartRuleView } from "./bindings/SmartRuleView";
export type { NearDupCluster } from "./bindings/NearDupCluster";
export type { NearDupMember } from "./bindings/NearDupMember";
export type { PersonView } from "./bindings/PersonView";
export type { SearchHitView } from "./bindings/SearchHitView";
export type { SearchRequest } from "./bindings/SearchRequest";
export type { SessionHandle } from "./bindings/SessionHandle";
export type { SourceView } from "./bindings/SourceView";
export type { TimelineCursor } from "./bindings/TimelineCursor";
export type { TimelineEntryView } from "./bindings/TimelineEntryView";
export type { TimelinePage } from "./bindings/TimelinePage";

import type { AlbumView } from "./bindings/AlbumView";
import type { AssetDetailView } from "./bindings/AssetDetailView";
import type { AssetFaceView } from "./bindings/AssetFaceView";
import type { ExportOptions } from "./bindings/ExportOptions";
import type { ExportReport } from "./bindings/ExportReport";
import type { IngestStatus } from "./bindings/IngestStatus";
import type { MapPoint } from "./bindings/MapPoint";
import type { MlStatus } from "./bindings/MlStatus";
import type { MlReindexReport } from "./bindings/MlReindexReport";
import type { PairingTicketView } from "./bindings/PairingTicketView";
import type { PeerAcceptedView } from "./bindings/PeerAcceptedView";
import type { ShareInviteView } from "./bindings/ShareInviteView";
import type { ShareRecipientView } from "./bindings/ShareRecipientView";
import type { IncomingShareView } from "./bindings/IncomingShareView";
import type { TripView } from "./bindings/TripView";
import type { MemoryGroupView } from "./bindings/MemoryGroupView";
import type { SmartAlbumView } from "./bindings/SmartAlbumView";
import type { SmartRuleView } from "./bindings/SmartRuleView";
import type { NearDupCluster } from "./bindings/NearDupCluster";
import type { PersonView } from "./bindings/PersonView";
import type { SearchHitView } from "./bindings/SearchHitView";
import type { SearchRequest } from "./bindings/SearchRequest";
import type { SessionHandle } from "./bindings/SessionHandle";
import type { SourceView } from "./bindings/SourceView";
import type { TimelineCursor } from "./bindings/TimelineCursor";
import type { TimelinePage } from "./bindings/TimelinePage";

export const api = {
    // --- auth -----------------------------------------------------------
    userExists: () => invoke<boolean>("user_exists"),
    createUser: (username: string, password: string) =>
        invoke<SessionHandle>("create_user", { username, password }),
    unlock: (username: string, password: string) =>
        invoke<SessionHandle>("unlock", { username, password }),
    lock: () => invoke<null>("lock"),
    unlockHidden: (password: string) =>
        invoke<boolean>("unlock_hidden", { password }),

    // --- sources --------------------------------------------------------
    addSource: (args: {
        name: string;
        root: string;
        adapter: "generic" | "iphone_folder" | "google_takeout";
        linkedOnly: boolean;
    }) =>
        invoke<number>("add_source", {
            name: args.name,
            root: args.root,
            adapter: args.adapter,
            linkedOnly: args.linkedOnly,
        }),
    listSources: () => invoke<SourceView[]>("list_sources"),
    ingestStatus: (sourceId: number) =>
        invoke<IngestStatus>("ingest_status", { sourceId }),

    // --- timeline -------------------------------------------------------
    timelinePage: (cursor: TimelineCursor | null, limit?: number) =>
        invoke<TimelinePage>("timeline_page", { cursor, limit: limit ?? null }),
    assetDetail: (id: number) =>
        invoke<AssetDetailView>("asset_detail", { id }),
    assetThumbnail: (id: number, size: number) =>
        invoke<number[]>("asset_thumbnail", { id, size }),
    assetOriginal: (id: number) =>
        invoke<number[]>("asset_original", { id }),

    // --- albums ---------------------------------------------------------
    createAlbum: (name: string, password: string | null) =>
        invoke<number>("create_album", { name, password }),
    listAlbums: (includeHidden: boolean) =>
        invoke<AlbumView[]>("list_albums", { includeHidden }),
    unlockAlbum: (id: number, password: string) =>
        invoke<boolean>("unlock_album", { id, password }),
    albumPage: (id: number, cursor: TimelineCursor | null, limit?: number) =>
        invoke<TimelinePage>("album_page", {
            id,
            cursor,
            limit: limit ?? null,
        }),
    addToAlbum: (id: number, assetIds: number[]) =>
        invoke<null>("add_to_album", { id, assetIds }),

    // --- export ---------------------------------------------------------
    exportAlbum: (id: number, dest: string, options: ExportOptions) =>
        invoke<ExportReport>("export_album", { id, dest, options }),

    // --- people ---------------------------------------------------------
    listPeople: (includeHidden?: boolean) =>
        invoke<PersonView[]>("list_people", {
            includeHidden: includeHidden ?? false,
        }),
    renamePerson: (personId: number, name: string) =>
        invoke<null>("rename_person", { personId, name }),
    hidePerson: (personId: number, hidden: boolean) =>
        invoke<null>("hide_person", { personId, hidden }),
    mergePeople: (src: number, dst: number) =>
        invoke<null>("merge_people", { src, dst }),
    splitPerson: (sourcePerson: number, faceIds: number[]) =>
        invoke<number>("split_person", { sourcePerson, faceIds }),
    personFaceThumbnail: (personId: number, size: number) =>
        invoke<number[]>("person_face_thumbnail", { personId, size }),
    assetFaces: (assetId: number) =>
        invoke<AssetFaceView[]>("asset_faces", { assetId }),

    // --- search ---------------------------------------------------------
    searchAssets: (request: SearchRequest) =>
        invoke<SearchHitView[]>("search_assets", { request }),

    // --- map ------------------------------------------------------------
    mapPoints: (
        afterDay: number | null,
        beforeDay: number | null,
        sourceId: number | null,
    ) =>
        invoke<MapPoint[]>("map_points", {
            afterDay,
            beforeDay,
            sourceId,
        }),

    // --- near-dup -------------------------------------------------------
    nearDupRebuild: () => invoke<number>("near_dup_rebuild"),
    nearDupList: () => invoke<NearDupCluster[]>("near_dup_list"),

    // --- ml -------------------------------------------------------------
    mlStatus: () => invoke<MlStatus>("ml_status"),
    mlModelsEnabled: () => invoke<boolean>("ml_models_enabled"),
    mlReindex: () => invoke<MlReindexReport>("ml_reindex"),

    // --- peers (Phase 3.1) ---------------------------------------------
    peerMyTicket: () => invoke<PairingTicketView>("peer_my_ticket"),
    peerAcceptTicket: (base32: string) =>
        invoke<PeerAcceptedView>("peer_accept_ticket", { base32 }),
    peerList: () => invoke<PeerAcceptedView[]>("peer_list"),
    peerForget: (nodeIdHex: string) =>
        invoke<boolean>("peer_forget", { nodeIdHex }),

    // --- share (Phase 3.2) ---------------------------------------------
    shareAlbumWithPeer: (albumId: number, peerNodeIdHex: string) =>
        invoke<ShareInviteView>("share_album_with_peer", { albumId, peerNodeIdHex }),
    listAlbumShares: (albumId: number) =>
        invoke<ShareRecipientView[]>("list_album_shares", { albumId }),
    revokeAlbumShare: (albumId: number, peerNodeIdHex: string) =>
        invoke<null>("revoke_album_share", { albumId, peerNodeIdHex }),
    listIncomingShares: () =>
        invoke<IncomingShareView[]>("list_incoming_shares"),
    acceptIncomingShare: (namespaceTicketBase32: string) =>
        invoke<number>("accept_incoming_share", { namespaceTicketBase32 }),

    // --- analytics (Phase 3.3+) ----------------------------------------
    detectTripsRun: () => invoke<number>("detect_trips_run"),
    listTrips: () => invoke<TripView[]>("list_trips"),
    memoriesOnThisDay: () =>
        invoke<MemoryGroupView[]>("memories_on_this_day"),

    // --- smart albums (D4) ---------------------------------------------
    createSmartAlbum: (name: string, rule: SmartRuleView) =>
        invoke<number>("create_smart_album", { name, rule }),
    listSmartAlbums: () => invoke<SmartAlbumView[]>("list_smart_albums"),
    refreshSmartAlbum: (id: number) =>
        invoke<number>("refresh_smart_album", { id }),
    deleteSmartAlbum: (id: number) =>
        invoke<boolean>("delete_smart_album", { id }),
    smartAlbumPage: (
        id: number,
        cursor: import("./bindings/TimelineCursor").TimelineCursor | null,
        limit?: number,
    ) =>
        invoke<import("./bindings/TimelinePage").TimelinePage>("smart_album_page", {
            id,
            cursor,
            limit: limit ?? null,
        }),
};

/// Decode a byte-array returned by `assetThumbnail` / `assetOriginal` into a
/// blob URL suitable for `<img src>` / `<video src>`.
export function bytesToBlobUrl(bytes: number[], mime: string): string {
    const u8 = new Uint8Array(bytes);
    return URL.createObjectURL(new Blob([u8], { type: mime }));
}
