// Typed IPC wrappers. Generated DTOs live in `./bindings/` (regenerated by
// `pnpm --filter app tauri` tests, or via `scripts/codegen_ts.sh`).
import { invoke } from "@tauri-apps/api/core";

export type { AlbumView } from "./bindings/AlbumView";
export type { AssetDetailView } from "./bindings/AssetDetailView";
export type { ExportOptions } from "./bindings/ExportOptions";
export type { ExportReport } from "./bindings/ExportReport";
export type { GpsView } from "./bindings/GpsView";
export type { IngestState } from "./bindings/IngestState";
export type { IngestStatus } from "./bindings/IngestStatus";
export type { SessionHandle } from "./bindings/SessionHandle";
export type { SourceView } from "./bindings/SourceView";
export type { TimelineCursor } from "./bindings/TimelineCursor";
export type { TimelineEntryView } from "./bindings/TimelineEntryView";
export type { TimelinePage } from "./bindings/TimelinePage";

import type { AlbumView } from "./bindings/AlbumView";
import type { AssetDetailView } from "./bindings/AssetDetailView";
import type { ExportOptions } from "./bindings/ExportOptions";
import type { ExportReport } from "./bindings/ExportReport";
import type { IngestStatus } from "./bindings/IngestStatus";
import type { SessionHandle } from "./bindings/SessionHandle";
import type { SourceView } from "./bindings/SourceView";
import type { TimelineCursor } from "./bindings/TimelineCursor";
import type { TimelinePage } from "./bindings/TimelinePage";

export const api = {
    // --- auth -----------------------------------------------------------
    userExists: () => invoke<boolean>("user_exists"),
    createUser: (username: string, password: string) =>
        invoke<SessionHandle>("create_user", { username, password }),
    unlock: (username: string, password: string) =>
        invoke<SessionHandle>("unlock", { username, password }),
    lock: () => invoke<null>("lock"),
    unlockHidden: (password: string) =>
        invoke<boolean>("unlock_hidden", { password }),

    // --- sources --------------------------------------------------------
    addSource: (args: {
        name: string;
        root: string;
        adapter: "generic" | "iphone_folder" | "google_takeout";
        linkedOnly: boolean;
    }) =>
        invoke<number>("add_source", {
            name: args.name,
            root: args.root,
            adapter: args.adapter,
            linkedOnly: args.linkedOnly,
        }),
    listSources: () => invoke<SourceView[]>("list_sources"),
    ingestStatus: (sourceId: number) =>
        invoke<IngestStatus>("ingest_status", { sourceId }),

    // --- timeline -------------------------------------------------------
    timelinePage: (cursor: TimelineCursor | null, limit?: number) =>
        invoke<TimelinePage>("timeline_page", { cursor, limit: limit ?? null }),
    assetDetail: (id: number) =>
        invoke<AssetDetailView>("asset_detail", { id }),
    assetThumbnail: (id: number, size: number) =>
        invoke<number[]>("asset_thumbnail", { id, size }),
    assetOriginal: (id: number) =>
        invoke<number[]>("asset_original", { id }),

    // --- albums ---------------------------------------------------------
    createAlbum: (name: string, password: string | null) =>
        invoke<number>("create_album", { name, password }),
    listAlbums: (includeHidden: boolean) =>
        invoke<AlbumView[]>("list_albums", { includeHidden }),
    unlockAlbum: (id: number, password: string) =>
        invoke<boolean>("unlock_album", { id, password }),
    albumPage: (id: number, cursor: TimelineCursor | null, limit?: number) =>
        invoke<TimelinePage>("album_page", {
            id,
            cursor,
            limit: limit ?? null,
        }),
    addToAlbum: (id: number, assetIds: number[]) =>
        invoke<null>("add_to_album", { id, assetIds }),

    // --- export ---------------------------------------------------------
    exportAlbum: (id: number, dest: string, options: ExportOptions) =>
        invoke<ExportReport>("export_album", { id, dest, options }),
};

/// Decode a byte-array returned by `assetThumbnail` / `assetOriginal` into a
/// blob URL suitable for `<img src>` / `<video src>`.
export function bytesToBlobUrl(bytes: number[], mime: string): string {
    const u8 = new Uint8Array(bytes);
    return URL.createObjectURL(new Blob([u8], { type: mime }));
}
